### ISSUE TITLE
Please add this software: Trace_y

### ISSUE THREAD

**Issue by wfxue** [AFM-SPM/afm-software-list#11]
Please replace ``null`` in the following template with quoted values (e.g. ``"Name": "TopoStats",``). Do so only where applicable (e.g. not every software has a Homepage).

```json
{
  "Name": Trace_y,
  "Description": Tracing filament polymers and individual filament 3D structural analysis algorithms.
  "Authors": Wei-Feng Xue,
  "Repository": github,
  "Homepage": http://github.com/wfxue/Trace_y,
  "Documentation": https://github.com/wfxue/Trace_y/blob/main/README.md,
  "Download Page": http://github.com/wfxue/Trace_y,
  "Coding Language": Matlab,
  "License": MIT,
  "Operating System": MacOS, Windows
  "Pricing Model": null
}
```

**Comment by paulmueller** [comment]
Hello,

please put the values in quotes, e.g. `"Trace_y"` instead of `Trace_y`.

Cheers!

**Comment by paulmueller** [comment]
You can find examples here: https://github.com/AFM-SPM/afm-software-list/tree/main/entries

**Comment by wfxue** [comment]
Thanks and sorry, I see how it works now. New entry submitted.
