### ISSUE TITLE
Update TopoStats details

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/afm-software-list#8]
Update TopoStats entry...

```json
{
  "Authors": "TopoStats Developers",
  "Coding Language": "Python",
  "Description": "An AFM image analysis program to batch process data and obtain statistics from images.",
  "Documentation": "https://afm-spm.github.io/TopoStats/",
  "Download Page": [
    "https://pypi.org/project/topostats/",
    "https://github.com/AFM-SPM/TopoStats/releases/"
  ],
  "Homepage": "https://afm-spm.github.io/TopoStats/",
  "License": "LGPL",
  "Name": "TopoStats",
  "Operating System": [
    "Linux",
    "Windows",
    "macOS"
  ],
  "Pricing Model": "FOSS",
  "Repository": "https://github.com/AFM-SPM/TopoStats"
}

**Comment by paulmueller** [comment]
Hey @ns-rse, can I convince you to create a PR (following the instructions in the "Contribution" section in the Readme)?

**Comment by ns-rse** [comment]
Hi,

Dpn't worry I need no convincing @paulmueller I've been working heavily on Topostats for almost a year. @alicepyne mentioned there was no description for TopoStats on wherever this page gets rendered/hosted (`https://afm-spm.github.io` didn't actually resolve for me).

I'm just canvassing input on wording from others who work on TopoStats.

**Comment by MaxGamill-Sheffield** [comment]
Is there a word limit? What about this as a little more explanative:
"An AFM image analysis program to batch process data by removing artefacts, identifying objects of interest, and obtaining and plotting topographic statistics."

**Comment by paulmueller** [comment]
FYI https://afm-spm.github.io/afm-software-list/
